// One entry per theme. Each palette names roles, never UI elements — the
// builder decides which workbench key a role lands on, so all themes stay in sync.
//
// Role cheat sheet:
//   appearance                           'dark' or 'light' — note it is NOT called
//                                        `type`, which is taken by the syntax role
//   bg / bgDim / bgElevated / bgOverlay  surfaces, from editor outward
//   fg / fgMuted / fgSubtle              text, from body to chrome to whisper
//   accent / accent2                     brand hues: focus, links, selection
//   keyword string func type constant    the five hues that carry syntax
//   variable property operator tag       supporting hues
//   parameter comment                    quiet italics
//   error warning info success           diagnostics, reused as ANSI + git
//
// Optional roles fall back to a sibling: number->constant, added->success,
// modified->info, deleted->error, builtin->func, decorator->accent2,
// regexp/escape->accent2, primitiveType->type, controlKeyword->keyword,
// punctuation->operator, languageVariable->constant.
//
// uniformL is the target OKLCH lightness for every syntax hue. Hues written
// below are authored for their hue and chroma; the build re-pitches their
// lightness so no color in a line of code is brighter than its neighbours.

module.exports = [
  {
    id: 'nocturne',
    label: 'Shades of Stoicism Nocturne',
    file: 'Shades-Nocturne-color-theme.json',
    appearance: 'dark',
    uniformL: 0.8,
    description: 'Deep indigo night. Vivid accents on a low-glare blue-violet base.',
    bg: '#191b28',
    bgDim: '#14151f',
    bgElevated: '#1e2131',
    bgOverlay: '#242840',
    border: '#2e3350',
    fg: '#cfd5f2',
    fgMuted: '#9aa2cc',
    fgSubtle: '#6b74a0',
    accent: '#82a8ff',
    accent2: '#c0a0ff',
    keyword: '#b98cff',
    controlKeyword: '#c99cff',
    string: '#a8dc86',
    func: '#82a8ff',
    type: '#ecc48d',
    constant: '#ffa06b',
    variable: '#cfd5f2',
    property: '#86d9ec',
    operator: '#8ad4f0',
    tag: '#fb8199',
    parameter: '#efb0d3',
    comment: '#6f7aa3',
    error: '#fb8199',
    warning: '#ecc48d',
    info: '#8ad4f0',
    success: '#a8dc86',
  },
  {
    id: 'aurora',
    label: 'Shades of Stoicism Aurora',
    file: 'Shades-Aurora-color-theme.json',
    appearance: 'dark',
    uniformL: 0.82,
    description: 'Arctic calm. Low-chroma steel and sage for long, quiet sessions.',
    bg: '#232936',
    bgDim: '#1d222d',
    bgElevated: '#28303e',
    bgOverlay: '#2e3849',
    border: '#3a4557',
    fg: '#d8e0ec',
    fgMuted: '#a6b2c4',
    fgSubtle: '#7d8b9e',
    accent: '#8fc1e3',
    accent2: '#b7a6d9',
    keyword: '#96b8de',
    controlKeyword: '#a8c6e8',
    string: '#b3cf92',
    func: '#93d6d2',
    type: '#e8cf9a',
    constant: '#c8a6d4',
    variable: '#d8e0ec',
    property: '#a9cade',
    operator: '#bcc9da',
    tag: '#e0959b',
    parameter: '#c9bade',
    comment: '#7e8da1',
    error: '#e0959b',
    warning: '#e8cf9a',
    info: '#8fc1e3',
    success: '#b3cf92',
  },
  {
    id: 'ember',
    label: 'Shades of Stoicism Ember',
    file: 'Shades-Ember-color-theme.json',
    appearance: 'dark',
    uniformL: 0.8,
    description: 'Warm retro terminal. Amber and olive on toasted charcoal, no blue glare.',
    bg: '#1f1d1a',
    bgDim: '#191715',
    bgElevated: '#24221e',
    bgOverlay: '#2b2823',
    border: '#3a352e',
    fg: '#e8dcc2',
    fgMuted: '#b3a68c',
    fgSubtle: '#8a806d',
    accent: '#f0bc52',
    accent2: '#ec9a7e',
    keyword: '#ec9a7e',
    controlKeyword: '#f2a98c',
    string: '#bfc971',
    func: '#f0bc52',
    type: '#8fc2ae',
    constant: '#dfa2b0',
    variable: '#e8dcc2',
    property: '#b6cfa4',
    operator: '#e0b077',
    tag: '#e8837c',
    parameter: '#d4bb8a',
    comment: '#93886f',
    error: '#e8837c',
    warning: '#f0bc52',
    info: '#8fc2ae',
    success: '#bfc971',
  },
  {
    id: 'mocha',
    label: 'Shades of Stoicism Mocha',
    file: 'Shades-Mocha-color-theme.json',
    appearance: 'dark',
    uniformL: 0.85,
    description: 'Soft pastels on warm plum. Gentle contrast that never shouts.',
    bg: '#1e1b26',
    bgDim: '#191620',
    bgElevated: '#23202c',
    bgOverlay: '#2a2636',
    border: '#383248',
    fg: '#dcd7ee',
    fgMuted: '#a9a2c4',
    fgSubtle: '#7b7498',
    accent: '#9ac0f7',
    accent2: '#c9aaf2',
    keyword: '#c9aaf2',
    controlKeyword: '#d4b9f7',
    string: '#a9dcbc',
    func: '#9ac0f7',
    type: '#f2d7a4',
    constant: '#f6bda6',
    variable: '#dcd7ee',
    property: '#a5dce6',
    operator: '#bfc9ee',
    tag: '#f4a6bd',
    parameter: '#edc3dd',
    comment: '#847ca2',
    error: '#f4a6bd',
    warning: '#f2d7a4',
    info: '#a5dce6',
    success: '#a9dcbc',
  },
  {
    id: 'abyss',
    label: 'Shades of Stoicism Abyss',
    file: 'Shades-Abyss-color-theme.json',
    appearance: 'dark',
    uniformL: 0.82,
    description: 'Near-black OLED contrast. Sharp, saturated hues for bright rooms.',
    bg: '#0b0d13',
    bgDim: '#07080d',
    bgElevated: '#101420',
    bgOverlay: '#161b2a',
    border: '#212838',
    fg: '#dbe4f2',
    fgMuted: '#93a0b8',
    fgSubtle: '#66738c',
    accent: '#56b6ff',
    accent2: '#d08cff',
    keyword: '#d08cff',
    controlKeyword: '#dba3ff',
    string: '#5fe3a1',
    func: '#56b6ff',
    type: '#ffd36e',
    constant: '#ffa05c',
    variable: '#dbe4f2',
    property: '#4fdfd0',
    operator: '#7fe6ff',
    tag: '#ff7090',
    parameter: '#ffaad8',
    comment: '#6b7890',
    error: '#ff7090',
    warning: '#ffd36e',
    info: '#56b6ff',
    success: '#5fe3a1',
  },
  {
    id: 'verdant',
    label: 'Shades of Stoicism Verdant',
    file: 'Shades-Verdant-color-theme.json',
    appearance: 'dark',
    uniformL: 0.82,
    description: 'Deep forest. Botanical greens with water blues and sunlit gold.',
    bg: '#151e1a',
    bgDim: '#111815',
    bgElevated: '#19241f',
    bgOverlay: '#1f2c26',
    border: '#2b3b33',
    fg: '#d6e4da',
    fgMuted: '#a1b5a8',
    fgSubtle: '#748d80',
    accent: '#7fc9d6',
    accent2: '#d3a2e8',
    keyword: '#d3a2e8',
    controlKeyword: '#ddb2f0',
    string: '#bcdc92',
    func: '#7fc9d6',
    type: '#e8cb85',
    constant: '#eca46f',
    variable: '#d6e4da',
    property: '#9fd8b4',
    operator: '#8ed0bb',
    tag: '#e89090',
    parameter: '#c6cf9c',
    comment: '#788f83',
    error: '#e89090',
    warning: '#e8cb85',
    info: '#7fc9d6',
    success: '#bcdc92',
  },
  {
    id: 'muted',
    label: 'Shades of Stoicism Muted',
    file: 'Shades-Muted-color-theme.json',
    appearance: 'dark',
    uniformL: 0.82,
    description: 'Low-color focus. Near-monochrome code, color reserved for strings and real problems.',
    bg: '#1b1e25',
    bgDim: '#16191f',
    bgElevated: '#20242c',
    bgOverlay: '#262b34',
    border: '#333944',
    fg: '#ccd3de',
    fgMuted: '#9aa3b1',
    fgSubtle: '#6e7887',
    accent: '#7fa8d8',
    accent2: '#b3a3cf',
    // Structure is carried by weight and italics here, not hue. Strings and
    // comments stay tinted because they are the two things you scan past.
    keyword: '#a7b3c6',
    controlKeyword: '#b6c0d1',
    string: '#9ec4a6',
    func: '#d2d9e4',
    type: '#c4c9d4',
    constant: '#c3b8a6',
    variable: '#ccd3de',
    property: '#bcc4d1',
    operator: '#8e99a9',
    tag: '#c2aeae',
    parameter: '#b2bac7',
    comment: '#6f7b8b',
    error: '#e08a90',
    warning: '#e0c184',
    info: '#84b6dd',
    success: '#96c9a0',
  },
  {
    id: 'daylight',
    label: 'Shades of Stoicism Daylight',
    file: 'Shades-Daylight-color-theme.json',
    appearance: 'light',
    uniformL: 0.5,
    description: 'Warm paper. Ink-grade contrast without the glare of pure white.',
    bg: '#fbf7f0',
    bgDim: '#f1eae0',
    bgElevated: '#f6f0e7',
    bgOverlay: '#ffffff',
    border: '#e0d6c6',
    fg: '#3a3833',
    fgMuted: '#6a6355',
    fgSubtle: '#8d8474',
    accent: '#1566a8',
    accent2: '#8b3fb0',
    keyword: '#8b3fb0',
    controlKeyword: '#7a37a0',
    string: '#3d7a2c',
    func: '#1566a8',
    type: '#94650a',
    constant: '#b04a12',
    variable: '#3a3833',
    property: '#0a6b70',
    operator: '#5c6470',
    tag: '#ad2a33',
    parameter: '#9c4381',
    comment: '#7f7767',
    error: '#bf2b1d',
    warning: '#94650a',
    info: '#1566a8',
    // Deliberately darker than the error red: red and green at matching
    // lightness are the one pairing a deuteranopic reader cannot resolve.
    success: '#2f6b28',
    onAccentFg: '#ffffff',
    badgeFg: '#ffffff',
  },
  {
    id: 'frost',
    label: 'Shades of Stoicism Frost',
    file: 'Shades-Frost-color-theme.json',
    appearance: 'light',
    uniformL: 0.5,
    description: 'Cool daylight. Crisp blue-grey surfaces with saturated, high-contrast code.',
    bg: '#f8fafd',
    bgDim: '#eef2f8',
    bgElevated: '#f2f6fb',
    bgOverlay: '#ffffff',
    border: '#dbe3ee',
    fg: '#2e3642',
    fgMuted: '#576273',
    fgSubtle: '#808d9e',
    accent: '#1a5fc8',
    accent2: '#7a33d6',
    keyword: '#7a33d6',
    controlKeyword: '#6d2ac4',
    string: '#177a4a',
    func: '#1a5fc8',
    type: '#a35a06',
    constant: '#b31e4b',
    variable: '#2e3642',
    property: '#0b6d85',
    operator: '#4a5769',
    tag: '#b8390d',
    parameter: '#9c1e9e',
    comment: '#6b7a8b',
    error: '#c62828',
    warning: '#a35a06',
    info: '#1a5fc8',
    success: '#0f6b41',
    onAccentFg: '#ffffff',
    badgeFg: '#ffffff',
  },
];
